sudo: required
services:
- docker
language: python
python:
- '3.5'
stages:
- name: test
- name: build and push docker image
jobs:
  include:
  - stage: test
    script:
    - bandit -r app.py -s B104
    - echo "Finished Testing"
  - stage: build and push docker image
    install: skip
    script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - export REPO="aravin008/flaskapp"
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$TAG .
    - docker image ls
    - echo "REPO:$REPO"
    - docker push $REPO
  - stage: deploy2
    env:
    - secure: Jkqx4zgPZcyJP6lRLBb6kDKbXy2HIWlBoWK6IZKJOqXMGaxNMkcZDPRlab8ccqneA050TFOyzSVDH74m8Tw3mXqfRLb8ZueEoMkPRd6BQYfi4mNGqrDg55vPwM33wkvd+Q711PHUsbyKcOQIs71GOiDpRdHmp2lVvef0SNIH5BdOoveDZ/sgjfrRsv9c7ZfPUgi86GnSIgz9Xc+PtQnF5faX/XalsyEgesrMJpT8cU9WY1Gdfw2nn3UqQxiJZBgwowZZBhjOa0UeXIkGXMTFHN2yv1ZGqIAGbpg2tsawo+SAm9XB58Y9D0ffjPxyfWk1cfEukjIhwG+P8VjM6x41fbymQgt5CQ31I+Fk8ft0STZapU/hGNSFzAozvCbHsBKSxgsx/TPayUyEL1PPviq/p7nexJlNI6bIliAvUwofK06ycskJso9M06Jngf4h7EDwjIlCktyM/hmJfUOsZ/418XeDQ2XOG+6eghAVIPH8c3aXo84GH8iHeLxceRvpVSSWfFIcSbo26dm2JMQuFkjFR5CqwpC4T699vGJgshONSzBDrl03QX2TiCwu3m0QbJBFVF3mlSka3QlFIOkm4aJ9e71W+6JElCVQVhRExRph0FZluW14rIvnyKE0sYJ6YfqG9CDpPPEkENJ/wXdxbmMOyXKPwXVcDA6G2+MFzuWEUzc=
    - secure: kdjLMhLrZ9sFNNuGSn6AynLdG7/FKge+DS4wP5nyxnTDzeQiCu0sn1U5i7ePC4zSaW6Q7IcAXJED0WTLLS6Aq4fC9Qo515nK+ehVE/K+KHsXxdwIWI93hLudjSH5I8fKwNGP2eNMLQ8UxdiNDFp2TMQiy4e8ag05t4C8kJYyyoBi6WfgWbdM1ECQNmDpDgfqEW3k3Q5xJfegenzQOHcXtrOfHIauOXBA2KciYQECFTztp19r62PFtbNhmJn1bY6uLDRm3Q0ZTCbD0ShrhcueVkInbBFCwu+jIjyWPyyjy/Dba1oTMGtFo1qDUcDuG5UNQ+KyCGvz9Of3qckJc2a3Msjr64M+4r7CDn2F7/30t/SgINMjsF6xDwGWpIfRE1wuz7o1cNiLk2L0M1vOliKEjYCCeSeEP8fJHbrAm3z8Klkm1PxCqlL9idX33h1/OJScGwBbCoolbWC3KUCHadzXU00aNA1nzYHf+ckkdbquGs98QrlCttyx6wAYhUY4/Fr0GnCPn9sBnCJCZLxJVHa1XXc7j2DKf9wvTidjyHYxSgySER1ThxGq2I3Baie5awQD76QdXGj+vOjLn2Jdk/eTwlOmyIh1+XCQegtjM8nD385BJFIrqcauJ+omvduGOnTBpT01iGEo49eBAUuovMxH5RUCSIIZHuaiEfK0eLeu54w=
    before_install:
    - openssl aes-256-cbc -K $encrypted_937fc597ef3a_key -iv $encrypted_937fc597ef3a_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    install: skip
    script:
    - chmod 400 "login_mar12.pem"
    - ls -al login_mar12.pem
    - scp -o "StrictHostKeyChecking no" -r -i "login_mar12.pem" mysql-img/my-sqlscript/createtable.sql
      $MACHINE:/home/ubuntu/
    - scp -o "StrictHostKeyChecking no" -r -i "login_mar12.pem" mysql-img/my-sqlscript/storedProcedure.sql
      $MACHINE:/home/ubuntu/
    - ssh  -o "StrictHostKeyChecking no" -i "login_mar12.pem" $MACHINE 'bash -s' <
      deploy.sh
