sudo: required
services:
- docker
language: python
python:
- '3.5'
stages:
- name: test
- name: build and push docker image
jobs:
  include:
  - stage: test
    script:
    - bandit -r app.py -s B104
    - echo "Finished Testing"
  - stage: build and push docker image
    install: skip
    script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - export REPO="aravin008/flaskapp"
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$TAG .
    - docker image ls
    - echo "REPO:$REPO"
    - docker push $REPO
  - stage: deploy2
    env:
    - secure: ea2XH4n5kmbhtatSH3uYpEfWTO6oZMhygz6kpCC3C9H1WlXih+/mNB0fNTvDaRlviifPdsUjl4ckhNrjUtIUwfco80fQlxissvsCJvCh2DqruZpqZciwbO6lOgvmqe1kJ0WMIZJqkzkrX06N1BZkeeBGCO18M0UEvK2/Adew6OBvt2kmJaYoHxftpHpqLhEaniiLiRvsvAScy7qKmfT5QrtR46PgV2i+tRKN3eCB+XxMOg3yjMvNNUSs8bC/GQ0en07LNPa63KYpYBWQftdd0f2zj1d9DLWCLsYuSCjdEXzzGtP/JudTDr10qWOm2h6E9B1bPile/J8km84rxXXoMhdN459AHhd3CAJAAMgB34QrARyYvwhsZuOvoBvsd/Bw4quEgUyvJW41nGWGyasy3xxVqY2mVWmVyTWI3hAdBoYuyaIw61nz9wNkuyLs+WtKgC0vcA/TQSgZmOjxaTGx9QfmB3V8wbaZIx9JGWQyv421iW3UKacNKeggLeFcggJnd5syFtfDfFzal22TpflGR63psfow5AuCRn9TwLXfKAjABwEHO9LzqGTSS+PCybC42rmO8JdcGnttJdn57XsKcni3Qtewh/JjJvHcpBnbVH5SHylKfZcPG71G6YgmFtHYAqAsG8wSVPb2KxZlST4Q90qkATbN+tgohFI4P79Ffz8=
    - secure: vU2g7A3SGzlb68wMdH3u9locMOIMnc/Mx18RSr5zVWZCW6hJKdHgJ2GDeYzz/Z7JuSFIYwuAgxYqYMWSJkZUFpZBTiW5MccRmTXcNKCy0OtFRBSDSZ6Cip/uHR2s0InHrjFB2fvzJRT71QWCdZiNVzy6wfX5NMETZhhTEG9sCW2gVI9gpjcEYznjyq70w3Q38WWGeVi0yDjcnaVICthUqc2qchgbynj7Ok6WMz3eroTbFJt8G3xpWpehGOoFu7NDBA0bCpaJkwJVXCKUSLX6g792YWGv50AZhbx3IOcE0/NtoFnVByYbDev7g+m952ib+vFE2jUpYNw/WOXdNIw2SX+1Zfgv1KBastvjtEHE7mRvToSAX6d9d0YQ766YEdKFeqJ45b7h1WUAG+IREbJ5ggeyNu7WZYqPdEodswERz1tbC+MOAF9AePhWUscGn7Wb89QNr+jhXQGT1szHJPY8x+BUSzm4INVayN3ozqIdLEro5+i97zVHORy4cvU3VXaqM56UPHIuta7G7eBYpBxTeUvs0iwJUusegO8D2IcQuM8zXxo+9hxxRmdsuJ6uWWGdgm1ZHi3cjLHtYyoinxuEw+R/EOtmlzgNDLoZdJJRf1j8FR8voy76F+2KPyUDqofqUBfcwM4uTVnY/h95WPbFWuyOTG/nJ99FIKmkEae7KbY=
    before_install:
    - openssl aes-256-cbc -K $encrypted_937fc597ef3a_key -iv $encrypted_937fc597ef3a_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    install: skip
    script:
    - chmod 400 "login_mar12.pem"
    - ls -al login_mar12.pem
    - scp -o "StrictHostKeyChecking no" -r -i "login_mar12.pem" mysql-img/my-sqlscript/createtable.sql
      $MACHINE:/home/ubuntu/
    - scp -o "StrictHostKeyChecking no" -r -i "login_mar12.pem" mysql-img/my-sqlscript/storedProcedure.sql
      $MACHINE:/home/ubuntu/
    - ssh  -o "StrictHostKeyChecking no" -i "login_mar12.pem" $MACHINE 'bash -s' <
      deploy.sh
env:
  global:
  - secure: FELdBQ2i9JA59bcWdvAIsXksQF0dUx214LK7wovqD/YSYBJKImGutfDg34YeA53O4SSX4YiHOEAsNDrYqVeizPhw1z2SpI4RUOUpQOP7wLPRyy9uWAVBs/OLXzkbn3jci1xWm9u2y4Am/9aME8V39axXQ0XdoitW42zJXDAfhdIbxOffp5rpQ2iRZFWrs72/1I/ETGb1GaPxHZKUEqby66qSrNwG7rzWmCxEhcr60eBpuRtp/lRVpGZb5k3MuUQNmBIPFwfdWn9mXj21i2/d9kju91scHMUWCkX26sYZTEqofdDnOYvu82bTdP/cU5pn0h9WQzTatEABzrDi33FLRBhRVi46iD9Jl0FFeA5XtVqQYpxtvQTnIFhEOhPYzAVEtde9r1Cl2JTAzRxBCfvQ7FHR7KIZVpHEsPSQj0kq7i6liTznB22N1NuVYk9TFZmrJPIOs2W8NxG9uoH7MTGZC7vMVo5GuuRZc8gml2eTk1TIE8K3iFpfomk3TpSPTCsPudzxKq96ReYpxw83ebhDGkzFh5iz/Nxnzu46AW0gopup5Vp/jmdIuGzYwyF+I78L/0NfllNO4VbkkJGaCfxP/WF34tNFZCa3vK2tV8Lxxp9TtKUqbklVU6/DVADhksd2NnIAKzA68kEkq5DitiiZIJByc3QVPTql88511XFvkTY=
  - secure: sEuD1uheNjPvmguqfwmw9IE0uMXPSaAEPpijK6wKbcxHVBRtTnUd/3XElH3qfh9JD9xmVOdlWD03nnXsBZp4zXX4MPqaSn8rE/Hw++vdkHdIPD1QE5OHHwKO/AgyzssTiF4wxsOMZGtmN+bSqhXZG8GzgwhF6gfAjVzGUIw/CVuOirsOuLpmHl7/p+brThP/WEAuVvSoj+EIG94u2x0wCQ3rJ6OYcY12JPqOCqjwySduc6T0SFI5PNyxJW7oeUxg1uK/cOC13Q9VvAOkgpfn7iYLFyK5zfeeN3wstNPjOf1INVghhR2HjN9pSQSobjM5ywX2EzCW5qvZqo9xET9jKI0UqoHMsW/aH9cqzghJr5y2ZDdNCwOFQlUcDKY+nqHFMr25E2k40zOdYSW6NM700nqaMKNRCej1PS+csjaiUHoSGr28UF1tiy64sKXOj+X/KFiMFBwspb8l8HRoWZ5AW78DwibKGCq6YvL2CroE7GK2UBCkQX8RHgZUT3lzDQqGVauSzuKwSrFJOQJNe2HmpviyK06jcE9FHmluDUhSFKPsqUZJmvBBfYmHZNw4fj3u1YK78En9EdWNRgoATZtGg2bOxnsMFMVJoT4PuBWr5+ZxGy4KwCv120L/mW4C/EF2yTQWkQNctDk7IQ8ZYuBzOUN8F+BxL0sejpEKSbP2hvQ=
